# Generated by Django 4.2.1 on 2023-05-27 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200)),
                ('course_description', models.TextField()),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('std_fname', models.CharField(max_length=30)),
                ('std_lname', models.CharField(max_length=30)),
                ('std_bod', models.DateField()),
                ('std_email', models.EmailField(max_length=254)),
                ('std_pnum', models.IntegerField()),
                ('std_nic', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('t_fname', models.CharField(max_length=30)),
                ('t_lname', models.CharField(max_length=30)),
                ('t_bod', models.DateField()),
                ('t_email', models.EmailField(max_length=254)),
                ('t_pnum', models.IntegerField()),
                ('t_nic', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherEnroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('t_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('std_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('salary_date', models.DateField()),
                ('t_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('std_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(through='main.StudentEnroll', to='main.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_ID',
            field=models.ManyToManyField(through='main.TeacherEnroll', to='main.teacher'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_date', models.DateTimeField()),
                ('course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('std_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
